language: node_js
node_js:
- '10'
os: linux
dist: bionic
jobs:
  include:
  - stage: "Frontend"
    before_script:
    - npm install -g @angular/cli@9
    - npm install
    script: 
      - ng build
    deploy:
      provider: releases
      token:
        secure: lNHkME+las3eL8GaTEy3uWcd0k8wtzc5q6m56tN4fYgaCS0Epxcux8TlNmhXm5dk7DSJtodM35Uml+dsWcCuu9pa2L4b0RcbbwkEKywIP2BBKgPaUz+9CkZkNP+JxFoUlFMwVQW2E8Uc1QDo/R1N4dQ3dF8Y6DWZbZFTGun/pAErmoYUsldx766ncMcWpwhBUD/CV2n9ZiCykdk4vs9a1NKUCrjmw+OwwdhJlUg/YrKVN34xut9P5ePWDPjuHl9geMqmlSgwgusPkFFmo4ArBdHziCcY3KZKs6Uw0oZ8qm+ECwjTna5EvG4g5SfVYbmT5zfptv3ulee+fKO39Qkn5AmeUsNPpmT8CGWxF6kybn+snWYIZLgr+NdMXratxyORia8RcOLvxYPUA9G9Za4aJJWBInUNshslHBpZv1skrZMi5wE9VYoLKuusa9PTzahkx2hzS1jf0QmbodGd0tJVtdI7sAXTlQzUzMt1BL7aX3CZp5YgNcfP3oQIfGZaru/HDdwXiNIX9dTOfBAvffdKzPOQjuU0NN1qKM+cFmw55Vo/VVVZSIxz0NMPPvfEke8gnmHxqPHEuNru+TPkP1/lSkNsMTVCG6EbNfmJfX5itN1R1d6N+gyZVmgx6FEaDTN9cRVCwZ0VctGMafstfdDpkvSmXH86SfCtfmIQOL0aTTg=
      file: "./dist"
      on:
        repo: alex4108/visitor-management
        branch: master
      cleanup: 'false'

